version: '3.3'

services:
  pyback:
    container_name: pyback
    image: sapfir0/premier-eye:cpu
    build:
      dockerfile: FastDockerfile
      context: .
    volumes:
      - ./data:/data
      - ./output:/output
    networks:
      - webpremiereye_some-net
    environment:
      - DOCKER_LOCAL_ADDRESS=http://172.20.0.1
    env_file:
      - .env


networks:
  webpremiereye_some-net:
    external: true