version: '3.1'

services:
  pyback:
    build:
      dockerfile: Dockerfile
      context: ./pyback

  redis:
    image: redis:alpine


  web:
    build: 
      dockerfile: Dockerfile
      context: ./pyfront
    ports:
    - "5000:5000"
    depends_on:
      - pyback
      - redis
