version: '3.3'

services:
  pyback:
    build:
      dockerfile: Dockerfile
      context: ./pyback
    command: python3 mainImage.py
    volumes:
      - ./pyback/data:/pyback/data
      - ./pyback/output:/pyback/output
# строчки выше не очень-то и адаптивны
  redis:
    image: redis:alpine
    ports:
      - "6379"

  web:
    build: 
      dockerfile: Dockerfile
      context: ./pyfront
    ports:
    - "5000:5000"
    depends_on:
      - pyback
      - redis
