version: '3.3'

services:
  pyback:
    container_name: pyback
    image: sapfir0/premier-eye:cpu
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./data:/data
      - ./output:/output
# строчки выше не очень-то и адаптивны
