version: '3.1'

services:
  pyback:
    build:
      dockerfile: Dockerfile
      context: ./pyback/docker/cpu

  pyfront:
    build: 
      dockerfile: Dockerfile
      context: ./pyfront
    depends_on:
      - pyback
