version: '3.1'

services:
  pyback:
    build:
      dockerfile: Dockerfile
      context: ./pyback

  pyfront:
    build: 
      dockerfile: Dockerfile
      context: ./pyfront
    command: flask run
    depends_on:
      - pyback
    ports:
    - 5000:5000 # [порт компьютера]:[порт контейнера]
