version: '3.3'

services:
  pyback:
    container_name: pyback
    image: sapfir0/premier-eye:cpu
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./data:/data
      - ./output:/output
    networks:
      - webpremiereye_some-net

networks:
  webpremiereye_some-net:
    external: true