version: '3.3'

services:
  pyback:
    image: sapfir0/premier-eye:cpu
    command: python3 mainImage.py
    volumes:
      - ./pyback/data:/pyback/data
      - ./pyback/output:/pyback/output
# строчки выше не очень-то и адаптивны
  redis:
    image: redis:alpine
    ports:
      - "6379"

  web:
    image: sapfir0/premier-eye:web
    command: flask run
    ports:
    - "5000:5000"
    depends_on:
      - pyback
      - redis
